1. 다음과 같은 행렬과 벡터의 연산을 하시오


(코드셀은 추가하여 사용, 프린트는 pprint함수를 사용할 것)

A = [[1,3],[5,4]] B = [[2,5],[6,7]] V = [[10],[20]]

A+B , A-B , 2A , 3v , AB, AC, Bv, B^3  

In [ ]:
# 행렬 a를 출력하는 함수
def pprint(msg, A):
  print("---msg---")
  (n,m) = A.shape
  for i in range(0,n):
    line = ""
    for j in range (0,m):
      line += "{0: .2f}".format(A[i,j])+ "\t"
    print(line)
  print("")

In [ ]:
import numpy as np

# 행렬 삽입
A = np.array([[1, 3], [5, 4]])
B = np.array([[2, 5], [6, 7]])
V = np.array([[10], [20]])

In [ ]:
# A + B 출력
result_add = A + B
pprint("A + B", result_add)

# A - B 출력
result_subtract = A - B
pprint("A - B", result_subtract)

# 2A 출력
result_double_A = 2 * A
pprint("2A", result_double_A)

# 3V 출력
result_triple_V = 3 * V
pprint("3V", result_triple_V)

# AB 출력 (행렬 곱)
result_AB = np.dot(A, B)
pprint("AB", result_AB)

# AC 출력 (행렬 곱)
C = np.array([[2, 1], [1, 3]])
result_AC = np.dot(A, C)
pprint("AC", result_AC)

# Bv 출력 (행렬 곱)
result_Bv = np.dot(B, V)
pprint("Bv", result_Bv)

# B^3 출력 (행렬 곱)
result_Bcubed = np.linalg.matrix_power(B, 3)
pprint("B^3", result_Bcubed)

---msg---
 3.00	 8.00	
 11.00	 11.00	

---msg---
-1.00	-2.00	
-1.00	-3.00	

---msg---
 2.00	 6.00	
 10.00	 8.00	

---msg---
 30.00	
 60.00	

---msg---
 20.00	 26.00	
 34.00	 53.00	

---msg---
 5.00	 10.00	
 14.00	 17.00	

---msg---
 120.00	
 200.00	

---msg---
 338.00	 485.00	
 582.00	 823.00	



2. 난수로 4X4 행렬 C를 구하고 행렬 C의 역행렬을 numpy의 두가지의 방식을 사용하여 구하고 행렬C 와 구한 역행렬의 곱이 단위행렬인지 확인하라.

In [ ]:
import numpy as np

# 4x4 무작위 행렬 C 생성
C = np.random.rand(4, 4)


In [ ]:
# 역행렬 구하기 - 첫 번째 방법 (np.linalg.inv 사용)
try:
    C_inv1 = np.linalg.inv(C)
except np.linalg.LinAlgError:
    # 역행렬이 존재하지 않는 경우 예외처리
    C_inv1 = None

# 역행렬 구하기 - 두 번째 방법 (np.linalg.pinv 사용)
C_inv2 = np.linalg.pinv(C)


In [ ]:
# 역행렬과 원래 행렬의 곱 계산
result1 = np.dot(C, C_inv1) if C_inv1 is not None else None
result2 = np.dot(C, C_inv2)


In [ ]:
# 단위 행렬인지 확인
is_identity1 = np.allclose(result1, np.identity(4)) if result1 is not None else False
is_identity2 = np.allclose(result2, np.identity(4))

In [ ]:
# 결과 출력
print("행렬 C:")
print(C)
print("\n첫 번째 방법으로 구한 역행렬:")
print(C_inv1)
print("\n두 번째 방법으로 구한 역행렬:")
print(C_inv2)
print("\n첫 번째 방법으로 구한 역행렬과 원래 행렬의 곱이 단위 행렬인가요?:", is_identity1)
print("\n두 번째 방법으로 구한 역행렬과 원래 행렬의 곱이 단위 행렬인가요?:", is_identity2)

행렬 C:
[[0.14304765 0.24699563 0.92789562 0.70084241]
 [0.30338303 0.66196934 0.77528067 0.77332341]
 [0.06295532 0.53285076 0.79139842 0.01770223]
 [0.33078836 0.40379763 0.33425489 0.13426524]]

첫 번째 방법으로 구한 역행렬:
[[ 1.41425576 -2.04170317 -1.59573814  4.58774413]
 [-2.4015489   2.38686035  1.04768202 -1.34996941]
 [ 1.50463473 -1.47896841  0.7070313   0.57120534]
 [-0.00753071  1.53364728 -0.97961758 -1.21689038]]

두 번째 방법으로 구한 역행렬:
[[ 1.41425576 -2.04170317 -1.59573814  4.58774413]
 [-2.4015489   2.38686035  1.04768202 -1.34996941]
 [ 1.50463473 -1.47896841  0.7070313   0.57120534]
 [-0.00753071  1.53364728 -0.97961758 -1.21689038]]

첫 번째 방법으로 구한 역행렬과 원래 행렬의 곱이 단위 행렬인가요?: True

두 번째 방법으로 구한 역행렬과 원래 행렬의 곱이 단위 행렬인가요?: True


3. 대각행렬 dag (3,4,5)를 생성하고 D11, D12, D21, D22를 사용한 블록행렬 D를 생성하라.


D11 = [[2,3],[4,5]] D12 = [[3],[4]] D21 = [[1,2]] D22 = [[6]]

In [ ]:
import numpy as np

# 대각행렬 생성
dag = np.diag([3, 4, 5])

# D11 생성
D11 = dag[:2, :2]

# D12 생성
D12 = dag[:2, 2:]

# D21 생성
D21 = dag[2:, :2]

# D22 생성
D22 = dag[2:, 2:]

# D 블록행렬 생성
D = np.block([[D11, D12], [D21, D22]])

In [ ]:
# 결과 출력
print("D11:")
print(D11)
print("\nD12:")
print(D12)
print("\nD21:")
print(D21)
print("\nD22:")
print(D22)
print("\n블록행렬 D:")
print(D)

D11:
[[3 0]
 [0 4]]

D12:
[[0]
 [0]]

D21:
[[0 0]]

D22:
[[5]]

블록행렬 D:
[[3 0 0]
 [0 4 0]
 [0 0 5]]


4. 3X3 영행렬, 모든 성분이 1인 4X2 행렬, 모든 성분이 3인 6X2행렬, 3X5 단위 행렬을 만들어 출력하는 프로그램을 작성하여라


In [ ]:
import numpy as np

# 3x3 영행렬 생성
zero_matrix = np.zeros((3, 3), dtype=int)

# 4x2 모든 성분이 1인 행렬 생성
ones_matrix = np.ones((4, 2), dtype=int)

# 6x2 모든 성분이 3인 행렬 생성
threes_matrix = np.full((6, 2), 3, dtype=int)

# 3x5 단위 행렬 생성
identity_matrix = np.eye(3, 5, dtype=int)

In [ ]:
# 결과 출력
print("3x3 영행렬:")
print(zero_matrix)

print("\n4x2 모든 성분이 1인 행렬:")
print(ones_matrix)

print("\n6x2 모든 성분이 3인 행렬:")
print(threes_matrix)

print("\n3x5 단위 행렬:")
print(identity_matrix)

3x3 영행렬:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

4x2 모든 성분이 1인 행렬:
[[1 1]
 [1 1]
 [1 1]
 [1 1]]

6x2 모든 성분이 3인 행렬:
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]

3x5 단위 행렬:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


5. E= [[1,2,3,4],[5,6,7,8],[9,10,11,12]] 행렬 E의 1행 3열의 성분, 2행 1열의 성분 1~2행의 2열에 해당하는 부분행렬을 출력하라.
행렬 E의 2행 1열 성분을 -1로 변경하고 행렬 E를 출력하라.


In [ ]:
import numpy as np

# 주어진 행렬 E
E = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
# 1행 3열의 성분 출력
element_1_3 = E[0, 2]
print("1행 3열의 성분:", element_1_3)

# 2행 1열의 성분 출력
element_2_1 = E[1, 0]
print("2행 1열의 성분:", element_2_1)

# 1~2행의 2열에 해당하는 부분행렬 출력
submatrix = E[0:2, 1:2]
print("1~2행의 2열에 해당하는 부분행렬:")
print(submatrix)


1행 3열의 성분: 3
2행 1열의 성분: 5
1~2행의 2열에 해당하는 부분행렬:
[[2]
 [6]]


In [ ]:
# 2행 1열 성분을 -1로 변경
E[1, 0] = -1

# 변경된 행렬 E 출력
print("2행 1열 성분을 -1로 변경한 행렬 E:")
print(E)


2행 1열 성분을 -1로 변경한 행렬 E:
[[ 1  2  3  4]
 [-1  6  7  8]
 [ 9 10 11 12]]
